---
name: Gerrit Merge

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

concurrency:
  # yamllint disable-line rule:line-length
  group: gerrit-merge-${{ github.workflow }}-${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

jobs:

  call-cmake-sonarqube-cloud:
    name: "SonarQube Cloud"
    # yamllint disable-line rule:line-length
    uses: modeseven-lfit/releng-reusable-workflows/.github/workflows/reuse-sonarqube-cloud.yaml@update-security-scans # Testing
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      # yamllint disable-line rule:line-length
      build_wrapper_url: "https://raw.githubusercontent.com/o-ran-sc/o-du-l2/refs/heads/main/sonarqube-cloud-build.sh"
      build_wrapper_out_dir: build/odu/bin/
      debug: true

  call-sonartype-lifecycle:
    name: "Sonatype Lifecycle Scan"
    # yamllint disable-line rule:line-length
    uses: modeseven-lfit/releng-reusable-workflows/.github/workflows/reuse-sonatype-lifecycle.yaml@update-security-scans # Testing
    secrets:
      NEXUS_IQ_PASSWORD: ${{ secrets.NEXUS_IQ_PASSWORD }}
    with:
      debug: true
      application_id: o-ran-sc-o-du-l2